server:
  port: ${GLANCE_PORT}
  proxied: true

theme:
  custom-css-file: /assets/user.css

pages:
  - name: Status
    columns:
      - size: full
        widgets:
          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Traefik Proxy
                url: http://traefik.localhost
                icon: si:traefikproxy
                allow-insecure: true
              - title: Infisical Secrets
                url: http://secrets.localhost
                icon: si:infisical
                allow-insecure: true
              - title: Beszel Monitoring
                url: http://beszel.localhost
                icon: si:speedtest
                allow-insecure: true
              - title: Dozzle Logs
                url: http://logs.localhost
                icon: si:docker
                allow-insecure: true
              - title: Metabase
                url: http://metabase.localhost
                icon: si:metabase
                allow-insecure: true                

          - type: docker-containers
            hide-by-default: false

  # Your existing home dashboard becomes the second page
  - $include: home.yml