#!/usr/bin/env bash
set -e

if [[ "$1" == "network" && "$2" == "inspect" ]]; then
  exit 0
fi

if [[ "$1" == "network" && "$2" == "create" ]]; then
  exit 0
fi

if [[ "$1" == "compose" ]]; then
  exit 0
fi

exit 0
