services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: unless-stopped
    networks:
      - home_network
    volumes:
      - home_memos_data:/var/opt/memos
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memos.rule=Host(`memos.${DOMAIN}`)"
      - "traefik.http.services.memos.loadbalancer.server.port=5230"
      - "traefik.docker.network=home_network"
    environment:
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5230/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  home_network:
    external: true

volumes:
  home_memos_data:
    name: home_memos_data
