#!/usr/bin/env python3
"""
Freqtrade strategy downloader helper.

Downloads official freqtrade strategies from:
    https://github.com/freqtrade/freqtrade-strategies/tree/main/user_data/strategies

This module downloads the official freqtrade strategies repository and copies
strategy files and folders into the user_data/strategies directory. This is
optional and can be enabled/disabled via a flag in entrypoint.py.

What this script does:
    1. Checks if custom strategies already exist (skips if they do)
    2. Downloads the freqtrade-strategies repository as a ZIP from GitHub
    3. Extracts the ZIP to a temporary directory
    4. Copies all strategy files (.py) and helper folders to user_data/strategies
    5. Cleans up temporary files

Why use this?
    - Official strategies are well-tested and maintained by the freqtrade team
    - Provides a good starting point for developing your own strategies
    - Can be used as reference implementations
    - Includes helper modules and indicator folders
    - Downloaded on first start if enabled (skipped on subsequent starts)
    - Non-destructive: existing custom strategies are not overwritten

Implementation details:
    - Uses urllib + zipfile (Python stdlib only, no external dependencies)
    - Dynamically locates the strategies folder in the extracted repo
    - Copies both .py files and folder structures (indicators, helpers, etc.)
    - Gracefully handles errors and continues if download fails

Usage example (called from entrypoint.py):
    from strategy_downloader import download_strategies
    
    if ENABLE_STRATEGY_DOWNLOAD:
        download_strategies()  # Returns True if successful or skipped

Environment:
    Expected to run inside the freqtrade Docker container at /freqtrade/user_data
    Temporary files extracted to /tmp/ and cleaned up automatically
"""

import urllib.request
import urllib.error
import zipfile
import shutil
from pathlib import Path

# Module-level configuration
REPO_ZIP_URL = "https://github.com/freqtrade/freqtrade-strategies/archive/refs/heads/main.zip"
REPO_STRATEGIES_RELATIVE_PATH = Path("user_data/strategies")  # Path within extracted repo

USER_DATA_DIR = Path("/freqtrade/user_data")
STRATEGIES_DIR = USER_DATA_DIR / "strategies"  # Destination: container's strategy directory
TEMP_DIR = Path("/tmp")  # Temporary extraction directory

# Feature flags
FORCE_DOWNLOAD_STRATEGIES = False  # Set to True to force re-download and overwrite existing strategies

# Log prefix for this module
LOG_PREFIX = "[strategy-downloader]"


def log(message: str, prefix: str = LOG_PREFIX) -> None:
    """Print a prefixed log message."""
    print(f"{prefix} {message}", flush=True)


def check_existing_strategies() -> bool:
    """
    Check if strategies already exist in the strategies directory.
    
    Excludes sample_strategy.py (auto-generated by freqtrade create-userdir).
    
    Returns:
        True if custom strategies exist (skip download), False otherwise
    """
    all_strategies = list(STRATEGIES_DIR.glob("*.py"))
    # Filter out sample_strategy.py as it's auto-generated on first init
    custom_strategies = [s for s in all_strategies if s.name != "sample_strategy.py"]
    
    if custom_strategies:
        log(f"Found {len(custom_strategies)} custom strategies. Skipping download.")
        return True
    return False


def download_zip(zip_path: Path) -> bool:
    """
    Download the freqtrade-strategies repository as a ZIP file from GitHub.
    
    Args:
        zip_path: Path where to save the downloaded ZIP file
    
    Returns:
        True if successful, False on error
    """
    try:
        log("Fetching repository...")
        urllib.request.urlretrieve(REPO_ZIP_URL, str(zip_path))
        return True
    except urllib.error.URLError as e:
        log(f"Warning: Failed to download repository: {e}")
        return False


def extract_zip(zip_path: Path, extract_path: Path) -> bool:
    """
    Extract the downloaded ZIP file to a temporary directory.
    
    GitHub ZIP archives contain a root folder (e.g., 'freqtrade-strategies-main')
    inside the ZIP. When extracted, this becomes a subdirectory in TEMP_DIR.
    
    The actual extracted folder path is discovered dynamically by find_strategies_folder()
    rather than hardcoding, so this works even if GitHub changes the naming convention.
    
    Args:
        zip_path: Path to the ZIP file to extract
        extract_path: Path where to extract the contents (not used but kept for API compatibility)
    
    Returns:
        True if successful, False on error
    """
    try:
        log("Extracting strategies...")
        # Extract to TEMP_DIR; GitHub ZIP will create a subfolder like 'freqtrade-strategies-main'
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(str(TEMP_DIR))
        
        # Verify extraction by finding the extracted directory
        extracted_dirs = list(TEMP_DIR.glob("freqtrade-strategies-*"))
        if extracted_dirs:
            actual_extract_path = extracted_dirs[0]
            log(f"Extracted to: {actual_extract_path.name}")
            # The actual path is found dynamically later in download_strategies()
            return True
        
        return True
    except zipfile.BadZipFile as e:
        log(f"Warning: Failed to extract ZIP: {e}")
        return False


def find_strategies_folder() -> Path | None:
    """
    Find the strategies folder in the extracted repository.
    
    GitHub ZIP archives extract with a root folder like 'freqtrade-strategies-main'.
    This function searches for the strategies folder regardless of the exact root
    folder name by looking for the expected relative path (defined in
    REPO_STRATEGIES_RELATIVE_PATH) within the extracted repo.
    
    Returns:
        Path to strategies folder if found, None otherwise
    """
    # Look for the extracted directory (GitHub zips use pattern: freqtrade-strategies-*)
    extracted_dirs = list(TEMP_DIR.glob("freqtrade-strategies-*"))
    
    for extracted_dir in extracted_dirs:
        # Use the module variable for the relative path
        strategies_path = extracted_dir / REPO_STRATEGIES_RELATIVE_PATH
        if strategies_path.exists():
            return strategies_path
    
    return None


def copy_strategies(strategies_src: Path) -> bool:
    """
    Copy strategy files and folders from the extracted repository to the user_data/strategies directory.
    
    This function copies:
    - All .py strategy files (e.g., sample_strategy.py, adx_strategy.py)
    - All supporting folders (e.g., indicators/, hyperopt/, etc.)
    
    Why folders? Official repo includes helper modules and custom indicator definitions
    that strategies may depend on. We copy everything to ensure strategies work correctly.
    
    If destination folders exist, they are overwritten (to get latest from repo).
    
    Args:
        strategies_src: Path to the strategies folder in the extracted repository
    
    Returns:
        True if successful, False on error
    """
    if not strategies_src.exists():
        log("Warning: strategies folder not found in downloaded repo")
        log(f"  Expected path: {strategies_src}")
        # Try to find it dynamically
        found_path = find_strategies_folder()
        if found_path:
            log(f"  Found at: {found_path}")
            strategies_src = found_path
        else:
            return False
    
    # Collect all files and directories
    all_items = list(strategies_src.iterdir())
    strategy_files = [item for item in all_items if item.is_file() and item.suffix == ".py"]
    strategy_dirs = [item for item in all_items if item.is_dir()]
    
    if not strategy_files and not strategy_dirs:
        log("Warning: No .py files or folders found in downloaded strategies folder")
        return False
    
    log(f"Copying {len(strategy_files)} strategy files and {len(strategy_dirs)} folders...")
    
    # Copy strategy files
    for strategy_file in strategy_files:
        try:
            dest_file = STRATEGIES_DIR / strategy_file.name
            shutil.copy2(strategy_file, dest_file)
            log(f"  ✓ Copied {strategy_file.name}")
        except Exception as e:
            log(f"  ✗ Failed to copy {strategy_file.name}: {e}")
    
    # Copy strategy folders
    for strategy_dir in strategy_dirs:
        try:
            dest_dir = STRATEGIES_DIR / strategy_dir.name
            # Remove destination if it exists (to overwrite)
            if dest_dir.exists():
                shutil.rmtree(dest_dir, ignore_errors=True)
            shutil.copytree(strategy_dir, dest_dir)
            log(f"  ✓ Copied folder {strategy_dir.name}/")
        except Exception as e:
            log(f"  ✗ Failed to copy folder {strategy_dir.name}: {e}")
    
    log(f"Successfully installed {len(strategy_files)} strategy files and {len(strategy_dirs)} folders")
    return True


def cleanup_temp_files(zip_path: Path, extract_path: Path) -> None:
    """
    Clean up temporary files created during download and extraction.
    
    Args:
        zip_path: Path to the downloaded ZIP file to delete
        extract_path: Path to the extracted directory to delete (may not match actual name)
    """
    try:
        if zip_path.exists():
            zip_path.unlink()
        
        # Clean up any extracted directories matching the pattern freqtrade-strategies-*
        for extracted_dir in TEMP_DIR.glob("freqtrade-strategies-*"):
            if extracted_dir.is_dir():
                shutil.rmtree(extracted_dir, ignore_errors=True)
    except Exception as e:
        log(f"Warning: Failed to cleanup temporary files: {e}")


def download_strategies() -> bool:
    """
    Download official freqtrade strategies from GitHub via ZIP file.
    
    Orchestrates the complete strategy download workflow:
        1. Check if strategies already exist (skip if they do, unless FORCE_DOWNLOAD_STRATEGIES=True)
        2. Download the freqtrade-strategies repository as ZIP from GitHub
        3. Extract the ZIP file to a temporary directory
        4. Copy strategy files to the user_data/strategies directory
        5. Clean up temporary files
    
    The FORCE_DOWNLOAD_STRATEGIES flag bypasses the existence check and forces
    re-download and overwrite of all strategies (useful for updating strategies).
    
    Returns:
        True if successful or skipped (strategies exist), False on error
    """
    # Check if strategies already exist (unless forced)
    if not FORCE_DOWNLOAD_STRATEGIES and check_existing_strategies():
        log("Skipping download (use FORCE_DOWNLOAD_STRATEGIES=True to re-download)")
        return True
    
    # If forcing download, log it
    if FORCE_DOWNLOAD_STRATEGIES:
        log("Force re-download enabled. Overwriting existing strategies...")
    
    log("Downloading official freqtrade strategies...")
    
    # Setup paths
    zip_path = TEMP_DIR / "freqtrade-strategies.zip"
    extract_path = TEMP_DIR / "freqtrade-strategies-main"
    strategies_src = extract_path / "user_data" / "strategies"
    
    try:
        # Download ZIP from GitHub
        if not download_zip(zip_path):
            return False
        
        # Extract ZIP
        if not extract_zip(zip_path, extract_path):
            return False
        
        # Find the actual strategies folder (dynamic lookup)
        found_strategies = find_strategies_folder()
        if not found_strategies:
            log("Warning: Could not locate strategies folder in downloaded repo")
            return False
        
        # Copy strategy files
        if not copy_strategies(found_strategies):
            return False
        
        return True
        
    except Exception as e:
        log(f"Warning: Unexpected error during strategy download: {e}")
        return False
    
    finally:
        # Always cleanup temporary files
        cleanup_temp_files(zip_path, extract_path)
