services:
  infra-postgres:
    image: postgres:latest
    container_name: infra_postgres
    restart: unless-stopped
    networks:
      - home_network
    ports:
      - "5432:5432"
    volumes:
      - home_infra_postgres_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${INFRA_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$$POSTGRES_USER", "-d", "$$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  home_network:
    external: true

volumes:
  home_infra_postgres_data:
    name: home_infra_postgres_data
