name: Home Server

services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --log.level=INFO
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    networks:
      - home_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    environment:
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  home_network:
    external: true
